### ISSUE TITLE
Method to generate stochastic Mujoco dataset

### ISSUE THREAD

**Issue by BaitingLuo** [marc-rigter/1R2R#1]
Hi Marc,

Amazing work! I wonder if there is any chance that you could share the code for generating the stochastic Mujoco dataset or give a hint of how this could be achieved with D4RL. Thank you very much!

**Comment by marc-rigter** [comment]
Hi there! Thanks for your interest in this work.

The Gym environments have been modified to add perturbation forces to the simulation (see [here]( https://github.com/marc-rigter/1R2R/blob/58d6cad436174a6a3b0b14880a3ce8742c0e3927/softlearning/environments/mujoco_stochastic/hopper_high_noise.py#L228)).

Then, I used a standard implementation of soft actor-critic to train an expert policy. Details on how the datasets are collected are in the appendix of the paper:

*We construct three datasets: Medium, Medium-Replay, and Medium-Expert. These are generated
in the same manner as the D4RL datasets [21]. The expert policy is a policy trained online using
SAC until convergence. The medium policy is trained until it obtains ≈ 40% of the performance of
the expert policy. The Medium-Replay dataset consists of the replay buffer collected while training
the medium policy. The Medium dataset contains transitions collected from rolling out the medium
policy. The Medium-Expert dataset contains a mixture of transitions generated by rolling out both the
medium and the expert policy*

I hope this helps!

**Comment by BaitingLuo** [comment]
This is so helpful! Thank you very much!
